### ISSUE TITLE
Recover from a disconnection with MQTT server

### ISSUE THREAD

**Issue by bilogic** [php-mqtt/client#136]
Hi,

The loop does not exit if here is a disconnection.
Any example on how to detect and recover? 

Thank you.

**Comment by bilogic** [comment]
I handled this a few ways in the past:

1. The loop can be configured to self-interrupt every 10 seconds, developer will check if still connected and react
2. The loop self-interrupts internally every X seconds and check if connected, otherwise exit the loop

**Comment by Namoshek** [comment]
Which version of the MQTT client are you running? Support for auto-reconnects was added in [`v1.3.0`](https://github.com/php-mqtt/client/releases/tag/v1.3.0) and [`v1.6.0`](https://github.com/php-mqtt/client/releases/tag/v1.6.0) improved on this by adding an option for the delay between reconnect attempts. In case of connection loss, after all reconnect attempts are used, the client will throw an exception. So I'm not sure where you are experiencing issues with a stuck loop.

Is it possible that you are connecting to a Docker or Kubernetes service, i.e. a virtual IP which load balances traffic?

**Comment by bilogic** [comment]
Hi, it is via packagist `1.7.0`

I restarted my mqtt server, but did not see the loop exit. Perhaps there could be a `onConnect` that accepts a closure which is also called when there is a `reconnect`?

**Comment by bilogic** [comment]
For further context, my client (C) is publishing a switch to homeassistant. After homeassistant is restarted, this switch shows up as disabled until C publishes the various topics of the switch again.

**Comment by Namoshek** [comment]
Ah ok, I see where you are coming from. There is currently no built-in way to detect reconnects, but this should be fairly simple to add. If you want to give it a try, feel free to create a PR (probably want to look into [`OffersHooks`](https://github.com/php-mqtt/client/blob/846f0de5c5713d947892998f868e6b28607fc0a0/src/Concerns/OffersHooks.php) and the [`MqttClient`](https://github.com/php-mqtt/client/blob/master/src/MqttClient.php) itself). Otherwise I'll see what I can do over the next days.

There might be a totally different solution to this problem though. Have you tried using the `retain` flag when publishing switches? As long as your MQTT broker has persistence enabled, such retained messages should survive a restart and should be published to subscribers immediately upon subscription.

https://github.com/php-mqtt/client/blob/846f0de5c5713d947892998f868e6b28607fc0a0/src/Contracts/MqttClient.php#L60-L72

**Comment by bilogic** [comment]
Hey thanks for getting back!

I read about the `retain` flag, but have trouble fully understanding it. Furthermore, the switch becoming disabled tells me something is wrong (which is a good thing). Let me try to find some time to look into the code.

Thank you!

**Comment by Namoshek** [comment]
The retain flag is an MQTT feature and not special to this library. All it does is to tell the broker that it should keep the message for the topic until a new message is published for the topic. It basically acts as simple state storage.

**Comment by bilogic** [comment]
@Namoshek I thought about this, can `php-mqtt` be configured to terminate whenever a disconnect has occurred? This way, your library can remain as-is while I handle the reconnection in my code.

**Comment by Namoshek** [comment]
@bilogic The client should do this with the default configuration already. If you disable auto-reconnect, an exception should be thrown whenever it fails connecting to the broker or when the connection gets lost. There might be some other options to fine-tune this though, like the connection timeout.

**Comment by bilogic** [comment]
@Namoshek thanks, I managed to solved my reconnection problem. Is there a way to perform an action periodically? (Let me know if I should open another issue)

**Comment by bilogic** [comment]
@Namoshek thank you for your help. I managed to understand MQTT better and resolved all my issues. Closing this.
