### ISSUE TITLE
No more message identifiers available. The queue is full.

### ISSUE THREAD

**Issue by jeeinn** [php-mqtt/client#178]
This error occurs after a few days of running the program, how can I avoid this problem?

Here is my code (v1.8.0)
```
$mqtt = new \Mqtt\InstanceController([
    'host'      =>  'test-mqtt.com', 
    'port'      =>  '1883',
    'clean_session' => false,
    'username'  =>  'username',
    'password'  =>  'password',
]);

while (true) {
    // reconnect
    if (!$this->mqttClient->isConnected()) {
        $clientId = $this->clientIdPre . '_' . time() . mt_rand(10000, 99999);
        $this->mqttClient = $mqtt->getMQClient($clientId);
        sleep(1);
        if ($this->mqttClient->isConnected()) echo_msg('mqttClient reconnect');
        continue;
    }
    
    try {
        $this->mqttClient->subscribe($topicConnected, function ($topic, $message) {
           printf(date('Y-m-d H:i:s') . " message on topic [%s]: %s\n", $topic, $message);
        }, $this->qos);
    } catch (\Exception $e) {
        echo_msg('subscribe Error: ' . $e->getMessage());
    }
    
    try {
        $this->mqttClient->loop();
    } catch (\Exception $e) {
        echo_msg('loop Error: ' . $e->getMessage());
    }
}
```

**Comment by Namoshek** [comment]
Not sure where some parts of the code come from (`\Mqtt\InstanceController` is definitely not from this library). However, the error sounds like you are using QoS 1 or 2 for _a lot of_ subscriptions and they are not being acknowledged by the broker.

Since I've no idea what you are trying to achieve, I don't think I can help you much right now. The only thing I can tell you is that running `$mqttClient->loop()` inside a `while (true) { ... }` loop is useless, since the `loop()` method is blocking. If you are somehow escaping the inner loop, you are producing a memory leak.

**Comment by jeeinn** [comment]
Thanks for the reply. I noticed the issue with `$mqttClient->loop()`, the reason I used  `while (true) { ... }` was because I needed to deal with some database connection timeouts. I think I should use `loopOnce(microtime(true), true)` instead of `loop()`.

**Comment by Namoshek** [comment]
Maybe, but then you shouldn't subscribe again all the time. The subscription will still be valid. `$mqtt->loopOnce()` is needed to fetch and deliver messages to your subscriptions.
