### ISSUE TITLE
Need a "sleep" before publishing message

### ISSUE THREAD

**Issue by melicerte** [php-mqtt/client#182]
Hi, 

First of all, thanks a lot for the great work on this lib !

I encounter a problem, which I think could be a misunderstanding on my part, since I don't understand the behaviour I'm facing.

I try to publish a message on a topic : 

```
            $server = 'myserver.eventgrid.azure.net';
            $port = 8883;
            $clientId = 'myclient';

            $mqtt = new MqttClient($server, $port, $clientId, MqttClient::MQTT_3_1_1);

            $connectionSettings = (new ConnectionSettings)
                ->setUsername('username')
                ->setConnectTimeout(5)
                ->setReconnectAutomatically(true)
                ->setUseTls(true)
                ->setTlsClientCertificateFile('certs/cert.pem')
                ->setTlsClientCertificateKeyFile('certs/cert.key')
            ;


            $mqtt->connect($connectionSettings);

           // If I don't use sleep() here, the message is never published on the MQTT broker, but no error is shown
            sleep(3);

            $mqtt->publish(
                'myawesometopic',
                json_encode(['message' => 'Hello'], JSON_THROW_ON_ERROR),
                MqttClient::QOS_AT_LEAST_ONCE
            );

            $mqtt->disconnect();
```

As I wrote in the code above, I had to wait a little before publishing the message, otherwise it would never be published nor received by the client subscribing the topic.
Could it be that the MQTT broker (on Azure EventGrid in my case) need "some" time before receiving messages after connection, or could it be something else in the lib explaining this behaviour ?

**Comment by Namoshek** [comment]
I immediately see an issue with the QoS you are using and how you are using the client in combination with that QoS, but I'm not certain that's the issue. It could be in combination with your static `$clientId = 'myclient'` (more regarding that later).

So you are using QoS 1 (`MqttClient::QOS_AT_LEAST_ONCE`) which means that the client sends the message and (this part is missing in your script) waits for an acknowledgement. If no acknowledgement is received within the configured timeout, the client will resend the message to the broker - that's why it is _at least once_. However, in order for the client to actually run this logic, you need to invoke `$mqtt->loop()` before disconnecting. By default, the `loop()` method will block infinitely, but you can also invoke it to circumvent this issue:

```php
$mqtt->loop(
    allowSleep: true,
    exitWhenQueuesEmpty: true,
    queueWaitLimit: 10
);
```

This will terminate the `loop()` method if all pending messages have been acknowledged, or after 10 seconds anyway.

So either switch to `MqttClient::QOS_AT_MOST_ONCE` or use the following script instead:

```php
$server = 'myserver.eventgrid.azure.net';
$port = 8883;
$clientId = 'myclient';

$mqtt = new MqttClient($server, $port, $clientId, MqttClient::MQTT_3_1_1);

$connectionSettings = (new ConnectionSettings)
    ->setUsername('username')
    ->setConnectTimeout(5)
    ->setReconnectAutomatically(true)
    ->setUseTls(true)
    ->setTlsClientCertificateFile('certs/cert.pem')
    ->setTlsClientCertificateKeyFile('certs/cert.key');

$mqtt->connect($connectionSettings);

$mqtt->publish(
    topic: 'myawesometopic',
    message: json_encode(['message' => 'Hello'], JSON_THROW_ON_ERROR),
    qualityOfService: MqttClient::QOS_AT_LEAST_ONCE
);

$mqtt->loop(
    allowSleep: true,
    exitWhenQueuesEmpty: true,
    queueWaitLimit: 10
);

$mqtt->disconnect();
```

---

**Why could a static client id in combination with QoS 1 or 2 be an issue?**

Whenever a fresh instance of the client is created, it creates an in-memory repository implicitly. The repository will store pending messages and also a counter for the message id that is used to address messages that are in-flight between the client and the broker (i.e. unfinished communication). A fresh repository always starts the counter at 1.

If the client now publishes the message and the broker never gets the chance to acknowledge that message, I would assume that (depending on its configuration) it might try to acknowledge the message after reconnection of the client. If the client immediately uses the same message id again, the broker might discard it since it could interpret it as being a resent message (even though it has not set this flag).

All of that is just a theory though. If you don't experience this issue with QoS 0 or above script with the added `loop()` call, then this would somewhat confirm this suspision. If the issue doesn't go away, I think there might be something else that's not visible in your (I assume) provided reduced example.

**Comment by melicerte** [comment]
Thanks for your answer, I'll look into it as soon as possible. For the record, I had the exact same issue with QoS 0.
I'll make more tests to elaborate.

**Comment by Namoshek** [comment]
On what platform are you running this code? And is it locally or on some kind of service like AWS Lambda?

**Comment by melicerte** [comment]
I'm running this code in a Docker container on my local computer (MacOS).
The MQTT broker is provided by Azure Event Grid.
The payload I try to publish is : 
`
{
  "type": "repair"
}
`

**Comment by melicerte** [comment]
I confirm that adding the loop resolves the issue.
Thanks a lot !

**Comment by melicerte** [comment]
Strange indeed ...
