### ISSUE TITLE
Subscribe and publish at the same time

### ISSUE THREAD

**Issue by RosiersRobin** [php-mqtt/client#80]
Hello,

I have an issue with the following;

I currently have an AWS IOT hub instance running, which I can subscribe and publish to with no issue. Now I kinda have the thing here that I need to publish and subscribe at the same time in a function.

So What I currently have is that I need to send a messae to an topic, that gets ctached by another service and that service broadcasts an message to another topic. That topic needs to be polled from the same function the first message was sent and when I get an message back, it can terminate the loop. I tried already to subscribe to an topic and then publish, but the message never gets sent, not can I receive any message. Anyone who has any idea on how I can achieve this?

**Comment by Namoshek** [comment]
This is a fairly common thing to do and it is called the RPC (_Remote Procedure Call_) pattern. I've answered very similar questions already in the past, see [here](https://github.com/php-mqtt/client/issues/66) and [here](https://github.com/php-mqtt/laravel-client/issues/13) (this one is for the [`php-mqtt/laravel-client`](https://github.com/php-mqtt/laravel-client), but works the same standalone).

The solution involves calling the appropriate functions in the following order:
- Connect to broker
- Subscribe to response topic
- Publish a command to the request topic
- Loop until a response has been received (or a timeout occurred)
- Disconnect (for best practice)

If you are using `QoS > 0`, looping will also ensure the subscription is placed correctly and the published message reaches its destination. `QoS > 0` is recommended for RPC to guarantee delivery. For an initial draft, I would recommend building something with `QoS = 0` though - because it is easier to spot bugs.

**Comment by RosiersRobin** [comment]
Yes, so that was what I thought, now, I do that, BUT, it doesn't seem to work.

My current code;

```

```

**Comment by RosiersRobin** [comment]
Finally found the issue.... I feel stupid like hell.

AWS has policy files, that was configured wrong.... Sorryyyyyyy

**Comment by Namoshek** [comment]
No worries, a configuration issue or QoS queue limit would have been my next guesses. 👍
