### ISSUE TITLE
Retrieving messages queued before subscribing using clean session

### ISSUE THREAD

**Issue by cpmargalef** [php-mqtt/client#88]
I'm trying to receive queued messages in php once I connect the client when the messages were published before this connection.  The $clean_session = false; and QoS = 1. What can I do to solve it? Here is my code:

$mqtt->connect($connectionSettings);

    $mqtt->subscribe('ecoes/DB/insert', function ($topic, $message) {
        global $conn;
        
        printf("Received message on topic [%s]: %s\n", $topic, $message);

        $msg_json = json_decode($message);

        $nombre_cliente = $msg_json->{'nombre_cliente'};
        $estado_LED = $msg_json->{'estado_LED'};
        $ip = $msg_json->{'ip'};
        $temperatura = $msg_json->{'temperatura'};
        $humedad = $msg_json->{'humedad'};

        $sql ="INSERT INTO db_test.info_led
        (nombre_cliente, estado_LED, IP_emisor, temperatura, humedad)
        VALUES
        ('$nombre_cliente',$estado_LED,'$ip',$temperatura,$humedad)
        ON DUPLICATE KEY UPDATE    
        estado_LED = $estado_LED, IP_emisor = '$ip', temperatura = $temperatura, humedad = $humedad
        ";
        $result = $conn->query($sql) or die($conn->error);
    
    }, 1);

**Comment by Namoshek** [comment]
If your client has not been connected to the broker before (with the same client id), using `$cleanSession = false` does not make a difference. It is a fresh session and the broker doesn't know the client. Only when reusing a session (by using the same client id again), the broker may be able to deliver messages received while the client was not connected.

To receive "old" messages on initial connect, you would want to use message retention. When publishing messages to an MQTT broker, it is possible to set the `retain` flag, which makes the broker keep the message until it is overwritten by a newer message on the same topic. Is the device publishing its data under your control?

**Comment by modulati0ns** [comment]
Hi @Namoshek. Yes, the devices publising data are under our control. This PHP client has been connected before, and can be connected to the broker. The steps that we are trying to reproduce are:

1st: Turn off the PHP subscriber client (the one shown in the @cpmargalef issue). (Stop de execution of the PHP)
2nd: Connect a Raspberry Pi client to the broker.
3rd: Publish various messages from the RPi to the topic: 'ecoes/DB/insert' with QoS 1.
4th: Turn on the PHP subscriber client. Subscribing to that mentioned topic and setting the clean_session flag to false, in order to try to obtain the messages published before from the RPi when the PHP client was not yed beign connected.

We shoud expect to receive in the PHP client, all the messages sent from the RPi since we think that's the behaviour when the clean session is set to false. but that's not the case and we don't receive anything.

We have tried the retain message option, but that only gives us the last message, and we want all the messages that has been sent by the RPi.

(Note: We know it is not problem of out broker (EMQX) since in the reverse way: PHP publish client to Python RPi subscriber, the process works perfectly)

**Comment by Namoshek** [comment]
Alright, I think you are hitting one of the limitations of the library right now. Subscriptions can only be made after connecting to the broker; but until the subscription is acknowledged by the broker, received messages are not delivered to the subscribed callback. I'm actually not sure this design is correct as it is, but I'm also not sure if I can change it without making it a breaking change.

Therefore I suggest a different solution which uses a hook to deliver the messages. Depending on your use case, the callback logic will be slightly more complex or not:

```php
// Create a new instance of an MQTT client and configure it to use the shared broker host and port.
// The client id is static in order for persistent sessions to work properly.
$client = new MqttClient(MQTT_BROKER_HOST, MQTT_BROKER_PORT, 'myclientid', MqttClient::MQTT_3_1);

// Register an event handler which is called whenever a message is received. In our case, we log every received message.
$handler = function (MqttClient $client, string $topic, string $message, int $qualityOfService, bool $retained) {
    // TODO: implement logic which parses and stores the message
};
$client->registerMessageReceivedEventHandler($handler);

// Connect to the broker without specific connection settings but without a clean session.
$client->connect(null, false);

// Subscribe to the topic 'foo/bar/baz' using QoS 1 but without callback since the message is handled elsewhere.
$client->subscribe('foo/bar/baz', null, MqttClient::QOS_AT_LEAST_ONCE);

// Since subscribing requires to wait for messages, we need to start the client loop which takes care of receiving,
// parsing and delivering messages to the registered callbacks. The loop will run indefinitely, until a message
// is received, which will interrupt the loop.
$client->loop(true);

// Gracefully terminate the connection to the broker.
$client->disconnect();
```

**Comment by cpmargalef** [comment]
Thank you! That was exactly what we needed and we could solve it. 

Greetings,
