### ISSUE TITLE
Subscribe doesn't work

### ISSUE THREAD

**Issue by fullstact69** [php-mqtt/client#91]
MQTT client's publish method has "retain" param. It is true or false. 

I change the payload data at publish method.

If "retain" param is true value, subscribe method is getting the changed data every time. 
But if "retain" param is false value, subscribe method is not getting the changed data.

How can I resolve this?

**Comment by Namoshek** [comment]
You should read up on [retained messages in MQTT](https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/), it is nothing special to this library.

The short version:

- **with `retain` flag:** the broker will keep the published message for the topic until a new message is published to the very same topic. The message is basically stored for the time being. If a client subscribes to the topic **_after_** the message has been published, the broker will send the retained (i.e. stored) message to the client immediately after subscribing.

- **without `retain` flag:** the broker does not store published messages. It delivers published messages only to clients which are subscribed to the topic at the very moment of publishing the message.
  - **edge case:** clients can be subscribed even when they are offline. A client may also receive not retained messages after reconnecting, as long as they use the same client id again and the `clean session` flag is not set.

**Comment by fullstact69** [comment]
Thank you for your answer. The situation is as follows:
IOT device is published the message with topic. My Website is subscribed the message with same topic, clientID. 
With retain flag, My website is received the message. 
But once retain flag is false, no more received the message. Subcribe function is read the lasted message in case of retain true value. 

For this situation, what do you think?

**Comment by fullstact69** [comment]
One more thing : Everytime I repeat to connect/disconnect after call the subscribe function.
And Google Chrome Extension - MQTTBox is always receive the message either the retain flag is set or not

**Comment by fullstact69** [comment]
I want to receive the message like MQTTBox extension

**Comment by Namoshek** [comment]
You are comparing apples and oranges. A normal web request takes somewhere between 50ms and 200ms. In order for this to work, your client must publish their message (without `retain` flag) within this exact window (or at least the broker needs to forward it in this window). The chrome extension on the other hand is a permanently running application, which will work regardless of the exact time when the message is published.

Simply put, relying on the message publisher to publish their message at a very specific time, is bad. It has all sorts of problems, from time synchronization to race conditions and you don't want to deal with those. Instead, there should be a long running process (a daemon) which subscribes to the topic and processes messages. This daemon can be a PHP script, no problem.

The ultimate question is: from where to where do we need to get what data? It might be possible that storing the received data in a database is an option, since you can then create a web server which returns data collected after a specific date given by the client. The client can then simply periodically ask the server for updates by passing the last collection time as parameter, for example.
